# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_isp'),
    ]

    operations = [
        migrations.AddField(
            model_name='isp',
            name='gen_practitioner',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='isp',
            name='legal_status',
            field=models.IntegerField(choices=[(1, 'Legally competent adult'), (2, 'Competent adult with informed support'), (3, 'Minor or adult with parent/relative as guardian'), (4, 'Minor or adult with non-relative as guardian or legally appointed guardian'), (5, 'Minor or adult with state as guardian')], default=1),
        ),
        migrations.AddField(
            model_name='isp',
            name='medi_care_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='isp',
            name='ndis_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='isp',
            name='primary_disability',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='isp',
            name='secondary_disability',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='isp',
            name='specialist',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='isp',
            name='funding',
            field=models.IntegerField(choices=[(1, 'NDIS'), (2, 'Over 65'), (3, 'Compensation'), (4, 'Other')], default=1),
        ),
    ]
