# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180721_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='existing_filled_form',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
