# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180721_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('relationship', models.CharField(max_length=1000)),
            ],
        ),
    ]
